version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
    groups:
      workflow-python:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: monthly
    groups:
      docs-python:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
    groups:
      python-lockfile:
        patterns:
          - "*"
