# USAGE:
#   This file will be used by the VS Code DevContainer extension
#   to create a development environment for the mdio-python project.
# HOW TO RUN TESTS
#    1. Open the project in VS Code.
#    2. Open the Command Palette (Ctrl+Shift+P) and select "Dev Containers: Reopen in Container".
#    3. Once the container is running, open a terminal in VS Code.
#    4. Run the tests using the command: `nox -s test`.
# HOW TO MANUALLY BUILD AND RUN THE CONTAINER
#    docker build -t mdio-dev -f .devcontainer/Dockerfile.dev .
#    docker run -it --rm --entrypoint /bin/bash --name mdio-dev mdio-dev
# NOTES:
#  1. The container will be run as the non-root user 'vscode' with UID 1000.
#  2. The virtual environment will be setup at /home/vscode/venv
#  3. The project source code will be mounted at /workspaces/mdio-python
ARG PYTHON_VERSION="3.13"
ARG LINUX_DISTRO="bookworm"
ARG UV_VERSION="0.6.11"
ARG NOX_VERSION="2025.2.9"
FROM mcr.microsoft.com/devcontainers/python:1-${PYTHON_VERSION}-${LINUX_DISTRO}

# Install git for nox pre-commit
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    git \
  && rm -rf /var/lib/apt/lists/*

ENV USERNAME="vscode"
USER $USERNAME

COPY --chown=$USERNAME:$USERNAME ./ /workspaces/mdio-python

WORKDIR /workspaces/mdio-python

ARG UV_VERSION
ARG NOX_VERSION
# https://devblogs.microsoft.com/ise/dockerizing-uv/
RUN python3 -m pip install --no-cache-dir uv==${UV_VERSION} nox==${NOX_VERSION}
# Prevent uv from trying to create hard links, which does not work in a container
# that mounts local file systems (e.g. VS Code Dev Containers)
ENV UV_LINK_MODE=copy
# Add path to the site-packages
ENV PYTHONUSERBASE=/home/$USERNAME/.local
ENV PATH="$PYTHONUSERBASE/bin:$PATH"

# Initialize virtual environment in the container
ENV VIRTUAL_ENV="/home/$USERNAME/.venv"
ENV UV_PROJECT_ENVIRONMENT=$VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN uv venv $VIRTUAL_ENV

# Install the project in the editable mode
# This allows for live reloading of the code during development
RUN uv pip install -e .
# Install "extras" (development dependencies) in pyproject.toml
RUN uv sync --group dev
# Now one can run:
#    pre-commit run --all-files
