# USAGE: 
#   This file will be used by the VS Code DevContainer extension 
#   to create a development environment for the mdio-python project.
# HOW TO RUN TESTS
#    1. Open the project in VS Code.
#    2. Open the Command Palette (Ctrl+Shift+P) and select "Dev Containers: Reopen in Container".
#    3. Once the container is running, open a terminal in VS Code.
#    4. Run the tests using the command: `nox -s test`.
# HOW TO MANUALLY BUILD AND RUN THE CONTAINER
#    docker build -t mdio-dev -f .devcontainer/Dockerfile.dev .
#    docker run -it --rm --entrypoint /bin/bash --name mdio-dev mdio-dev
# NOTES: 
#  1. The container will be run as the non-root user 'vscode' with UID 1000.
#  2. The virtual environment will be setup at /home/vscode/venv 
#  3. The project source code will be mounted at /workspaces/mdio-python
ARG PYTHON_VERSION="3.13"
ARG LINUX_DISTRO="bookworm"
ARG UV_VERSION="0.6.11"
ARG NOX_VERSION="2025.2.9"
FROM mcr.microsoft.com/devcontainers/python:1-${PYTHON_VERSION}-${LINUX_DISTRO}

# Install git for nox pre-commit
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    git \
  && rm -rf /var/lib/apt/lists/*

ENV USERNAME="vscode"
USER $USERNAME

# # Add path to the user-installed packages
# ENV PYTHONUSERBASE=/home/$USERNAME/.local
# ENV PATH="$PYTHONUSERBASE/bin:$PATH"

COPY --chown=$USERNAME:$USERNAME ./ /workspaces/mdio-python

WORKDIR /workspaces/mdio-python

ARG UV_VERSION
ARG NOX_VERSION
RUN python3 -m pip install uv==${UV_VERSION} nox==${NOX_VERSION} msgpack ipykernel

# Initialize virtual environement in the container
ENV VIRTUAL_ENV="/home/$USERNAME/venv"
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# installing pytest is required for VS Code Python Testing
RUN pip install pytest pytest-cov pytest-mock pytest-asyncio
# install packages required to run `pre-commit run --all-files`
RUN pip install ruff pre-commit pre-commit-hooks

# Install the project in editable mode
# This allows for live reloading of the code during development
RUN pip install -e .

# RUN uv pip install snakeviz






